{
 "title": "Siłownie Eltek",
 "tags": [
  "eltek",
  "power"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Eltek",
    "query": "show tag values with key = \"eltek_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Battery voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\")/100 FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'BatteryVoltageValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "BatteryVoltageValue" }
     ]
    }
   ]
  },
  {
   "title": "Battery current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Battery current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\")/10 FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'BatteryCurrentsValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "BatteryCurrentsValue" }
     ]
    }
   ]
  },
  {
   "title": "Battery temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Battery temperature",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\") FROM /wide-net.eltek.$server.battery.temperature/ WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "BatteryTemperaturesValue" }
     ]
    }
   ]
  },
  {
   "title": "Battery time left",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Battery time left",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\") FROM /wide-net.eltek.$server.battery.timeleft/ WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "BatteryTimeLeftValue" }
     ]
    }
   ]
  },
  {
   "title": "Battery quality",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Battery quality",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\") FROM /wide-net.eltek.$server.battery.quality/ WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "BatteryQualityValue" }
     ]
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Ah" }
   ],
   "targets": [
    {
     "alias": "Battery total capacity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\") FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'BatteryTotalCapacityValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "BatteryTotalCapacityValue" }
     ]
    },
    {
     "alias": "Battery remaining capacity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wide-net.eltek.eltek-pawilon.voltage.battery",
     "query": "SELECT mean(\"value\") FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'BatteryTotalRemainingValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery used capacity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wide-net.eltek.eltek-pawilon.voltage.battery",
     "query": "SELECT mean(\"value\") FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'BatteryUsedCapacityValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mains voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Mains voltage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\") FROM /wide-net.eltek.$server.mains.voltage/ WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "MainsVoltage" }
     ]
    }
   ]
  },
  {
   "title": "Load current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Load current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\")/10 FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'LoadCurrentValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "LoadCurrentValue" }
     ]
    }
   ]
  },
  {
   "title": "Load power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Load power",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\")/1000 FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'LoadPower') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "LoadPower" }
     ]
    }
   ]
  },
  {
   "title": "Rectifier(s) voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_measurement_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\") FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" =~ /RectifierInputVoltageValue.[0-9]/) AND $timeFilter GROUP BY time($interval), \"measurement_type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "RectifierInputVoltageValue.1" }
     ]
    }
   ]
  },
  {
   "title": "Rectifiers current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "amp", "label": "Ampers" }
   ],
   "targets": [
    {
     "alias": "$tag_measurement_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\")/10 FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" =~ /RectifierOutputCurrentValue.[0-9]/) AND $timeFilter GROUP BY time($interval), \"measurement_type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "RectifierOutputCurrentValue.1" }
     ]
    }
   ]
  },
  {
   "title": "Rectifiers total current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "amp", "label": "Ampers" }
   ],
   "targets": [
    {
     "alias": "Total current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eltek",
     "query": "SELECT mean(\"value\")/10 FROM \"rp_1_month\".\"eltek\" WHERE (\"eltek_name\" =~ /^$server$/ AND \"measurement_type\" = 'RectifiersCurrentValue') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "eltek_name", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "measurement_type", "operator": "=", "value": "RectifiersCurrentValue" }
     ]
    }
   ]
  }
 ]
}